# Generated by Django 5.2 on 2025-05-01 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshiprelationship',
            name='mentee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentored', to=settings.AUTH_USER_MODEL),
        ),
    ]
