# Generated by Django 5.2 on 2025-05-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
