# Generated by Django 5.2 on 2025-05-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_successstory_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportgroup',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the participant', null=True),
        ),
    ]
