# Generated by Django 5.2 on 2025-05-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_supportgroup_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportgroupparticipant',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
