# Generated by Django 5.2 on 2025-05-04 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_supportgroupparticipant_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipprogram',
            name='facilitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_programs', to=settings.AUTH_USER_MODEL),
        ),
    ]
