# Generated by Django 5.2 on 2025-05-04 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_mentorshipprogram_facilitator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshipprogram',
            name='facilitator',
        ),
    ]
